In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

import numpy as np
from sklearn.datasets import load_digits

In [3]:
digits = load_digits()

In [12]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(digits.data , digits.target , test_size= 0.3)

In [13]:
lr = LogisticRegression()
lr.fit(x_train , y_train)
lr.score(x_test , y_test)

/Users/ha5hkat/PROGRAMS/PyGround/pyplay/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [14]:
svm = SVC()
svm.fit(x_train , y_train)
svm.score(x_test , y_test)

0.9925925925925926

In [15]:
rf = RandomForestClassifier()
rf.fit(x_train , y_train)
rf.score(x_test , y_test)

0.975925925925926

K Fold Cross Validation

In [16]:
from sklearn.model_selection import KFold    

In [26]:
kf = KFold(n_splits= 4)

In [27]:
for train_index , test_index  in kf.split([0,1,2,3,4,5,6,7,8,9]) :
    print(train_index , test_index)

[3 4 5 6 7 8 9] [0 1 2]
[0 1 2 6 7 8 9] [3 4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [28]:
def get_score(model , x_train , x_test , y_train , y_test) :
    model.fit(x_train , y_train)
    return model.score(x_test , y_test)

In [29]:
get_score(LogisticRegression() , x_train , x_test , y_train , y_test)

/Users/ha5hkat/PROGRAMS/PyGround/pyplay/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9666666666666667

In [63]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)


In [43]:
scores_lr = []
scores_svm = []
scores_rf = []

In [44]:
for train_index , test_index in skf.split(digits.data , digits.target) :
    x_train , x_test , y_train , y_test = digits.data[train_index] , digits.data[test_index] , digits.target[train_index] , digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression() , x_train , x_test , y_train , y_test))
    scores_svm.append(get_score(SVC() , x_train , x_test , y_train , y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40) , x_train , x_test , y_train , y_test))
    

/Users/ha5hkat/PROGRAMS/PyGround/pyplay/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ha5hkat/PROGRAMS/PyGround/pyplay/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modul

In [45]:
print(scores_lr)

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]


In [46]:
print(scores_svm)

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]


In [47]:
print(scores_rf)

[0.9398998330550918, 0.9415692821368948, 0.9282136894824707]


In [64]:
from sklearn.model_selection import cross_val_score

In [71]:
cross_val_score(LogisticRegression() , digits.data , digits.target , cv= 3)

/Users/ha5hkat/PROGRAMS/PyGround/pyplay/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ha5hkat/PROGRAMS/PyGround/pyplay/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modul

array([0.92153589, 0.94156928, 0.91652755])

In [81]:
cross_val_score(SVC() , digits.data , digits.target , cv = 3)


array([0.96494157, 0.97996661, 0.96494157])

In [80]:
cross_val_score(RandomForestClassifier(n_estimators=40) , digits.data , digits.target,cv=3)


array([0.92320534, 0.94824708, 0.93155259])

In [79]:
cross_val_score(RandomForestClassifier(n_estimators=10) , digits.data , digits.target,cv=3)


array([0.91318865, 0.89649416, 0.88313856])

In [78]:
cross_val_score(RandomForestClassifier(n_estimators=5) , digits.data , digits.target , cv=3)


array([0.84974958, 0.88146912, 0.83639399])

In [77]:
cross_val_score(RandomForestClassifier(n_estimators=60) , digits.data , digits.target, cv = 3)


array([0.92487479, 0.94991653, 0.92487479])